import { AnalyzedArticle, GlobePoint } from '@/types';

function uid(): string {
  return Math.random().toString(36).substring(2, 9);
}

function art(
  title: string, description: string, url: string,
  sourceName: string, sourceUrl: string,
  summary: string, genre: string,
  reliability_score: number, sentiment: number,
  veracity: 'VERIFIED' | 'UNVERIFIED' | 'SENSATIONALIST' = 'VERIFIED',
  offsetMs = 0
): AnalyzedArticle {
  return {
    id: uid(), title, description, content: '', url, image: null,
    publishedAt: new Date(Date.now() - offsetMs).toISOString(),
    source: { name: sourceName, url: sourceUrl },
    summary, genre, reliability_score, sentiment, veracity,
  };
}

export function getMockArticles(countryCode: string): AnalyzedArticle[] {
  const sets: Record<string, AnalyzedArticle[]> = {

    // ── Americas ─────────────────────────────────────────────────────────────
    US: [
      art('Fed Signals Rate Cut Path as Inflation Cools to 2.4%', 'Federal Reserve pivots dovish amid cooling CPI data.', 'https://example.com/us-fed', 'Reuters', 'https://reuters.com', 'Federal Reserve officials signalled a rate cut pathway as CPI fell to 2.4%, marking the closest approach to the 2% target in 3 years. Markets rallied sharply on the news.', 'Monetary Policy', 92, 0.55, 'VERIFIED', 0),
      art('Silicon Valley Layoffs: Tech Sector Sheds 80k Jobs in Q1', 'Major tech firms announce further workforce reductions.', 'https://example.com/us-tech', 'WSJ', 'https://wsj.com', 'US technology companies shed 80,000 jobs in Q1, continuing a wave of post-pandemic corrections. AI automation and rising capital costs are cited as key drivers.', 'Corporate Intelligence', 88, -0.60, 'VERIFIED', 3600000),
      art('Congress Passes $95bn Foreign Aid Package for Ukraine and Israel', 'Bipartisan bill clears Senate after months of gridlock.', 'https://example.com/us-aid', 'AP News', 'https://apnews.com', 'The US Congress passed a $95 billion foreign aid package, allocating funds to Ukraine, Israel, and Taiwan. The bill passed with rare bipartisan support after prolonged delay.', 'Geopolitical Tension', 90, -0.20, 'VERIFIED', 7200000),
    ],
    CA: [
      art('Bank of Canada Cuts Rate to 4.5% — First in 4 Years', 'BoC pivots as inflation retreats toward target.', 'https://example.com/ca-boc', 'CBC News', 'https://cbc.ca', 'The Bank of Canada cut its benchmark rate to 4.5%, the first reduction since the pandemic era. Governor Macklem cited sustained disinflation and a cooling labour market.', 'Monetary Policy', 93, 0.40, 'VERIFIED', 0),
      art('Canada Unveils $15bn Housing Accelerator to Build 100k Homes', 'Federal plan fast-tracks zoning and developer financing.', 'https://example.com/ca-housing', 'Globe and Mail', 'https://theglobeandmail.com', 'Ottawa announced a $15 billion housing fund targeting 100,000 new units by 2026. The program bypasses slow municipal zoning, offering direct federal-to-builder financing.', 'Domestic Policy', 87, 0.55, 'VERIFIED', 5400000),
      art('Trudeau Minority Government Faces Confidence Vote', 'NDP withdraws supply agreement, triggering political crisis.', 'https://example.com/ca-politics', 'National Post', 'https://nationalpost.com', 'Prime Minister Trudeau faces a non-confidence motion after the NDP ended its support agreement. Polls show Conservatives leading by 18 points ahead of a potential snap election.', 'Domestic Policy', 86, -0.45, 'VERIFIED', 10800000),
    ],
    BR: [
      art('Brazil\'s Petrobras Reports $28bn Profit, Doubles Dividend', 'State oil company posts record earnings on high crude prices.', 'https://example.com/br-petrobras', 'Folha de S.Paulo', 'https://folha.uol.com.br', 'Petrobras reported a $28 billion annual profit, its second-highest ever, and doubled its dividend payout. Lula government faces pressure over how to deploy the windfall.', 'Corporate Intelligence', 84, 0.50, 'VERIFIED', 0),
      art('Amazon Deforestation Drops 50% Under Lula\'s First Year', 'Satellite data shows dramatic reversal under new environmental policies.', 'https://example.com/br-amazon', 'O Globo', 'https://oglobo.globo.com', 'Brazil\'s Amazon deforestation fell 50% in Lula\'s first year, compared to the final year of the Bolsonaro government. The reversal is being hailed as a landmark environmental achievement.', 'Environmental Crisis', 88, 0.70, 'VERIFIED', 5400000),
      art('Real Strengthens as Brazil\'s Inflation Falls Below 3%', 'Central bank eyes rate cuts as economic outlook improves.', 'https://example.com/br-economy', 'Valor Econômico', 'https://valor.globo.com', 'Brazil\'s annual inflation fell to 2.9%, its lowest in six years, boosting the Real and fuelling speculation of Banco Central rate cuts. GDP growth is tracking at 2.8% for the year.', 'Monetary Policy', 82, 0.45, 'VERIFIED', 10800000),
    ],
    MX: [
      art('Mexico\'s Claudia Sheinbaum Wins Presidency by Historic Margin', 'First female president-elect takes 59% of the vote.', 'https://example.com/mx-election', 'El Universal', 'https://eluniversal.com.mx', 'Claudia Sheinbaum of the ruling Morena party won Mexico\'s presidency with 59% of the vote, a historic margin. She becomes Mexico\'s first-ever female president.', 'Domestic Policy', 89, 0.60, 'VERIFIED', 0),
      art('Nearshoring Boom Drives Mexico\'s FDI to Record $36bn', 'US-China decoupling fuels manufacturing investment surge.', 'https://example.com/mx-fdi', 'Reforma', 'https://reforma.com', 'Foreign direct investment into Mexico hit a record $36 billion as manufacturers rush to nearshore production closer to the US market amid US-China trade tensions.', 'Economic Outlook', 85, 0.65, 'VERIFIED', 5400000),
      art('Cartels Expand Control Over Mexico\'s Avocado Industry', 'Organised crime extorts farmworkers across Michoacán.', 'https://example.com/mx-cartel', 'AP News', 'https://apnews.com', 'Criminal organisations now control large portions of Mexico\'s booming avocado export industry, extorting farmers and in some cases running entire growing operations.', 'Geopolitical Tension', 80, -0.70, 'SENSATIONALIST', 10800000),
    ],

    // ── Europe ───────────────────────────────────────────────────────────────
    GB: [
      art('Bank of England Holds at 5.25% Amid Services Inflation', 'MPC votes 8-1 to hold as core prices stay sticky.', 'https://example.com/gb-boe', 'BBC News', 'https://bbc.co.uk', 'The Bank of England held rates at 5.25%, with eight MPC members voting to hold. Governor Bailey noted services inflation remains above target despite headline CPI cooling.', 'Monetary Policy', 94, -0.20, 'VERIFIED', 0),
      art('London Tech Week: UK Startups Raise £6bn in 2024', 'British AI and fintech sectors lead European venture activity.', 'https://example.com/gb-tech', 'The Guardian', 'https://theguardian.com', 'UK technology startups raised £6 billion across 2024, with AI and fintech leading the charge. London retained its position as Europe\'s top tech funding hub despite Brexit headwinds.', 'Climate Technology', 84, 0.65, 'VERIFIED', 5400000),
      art('UK General Election: Labour Wins Landslide After 14 Years', 'Keir Starmer becomes Prime Minister with 400+ seat majority.', 'https://example.com/gb-election', 'The Times', 'https://thetimes.co.uk', 'Labour won a historic landslide in the UK General Election, ending 14 years of Conservative rule. Keir Starmer begins as Prime Minister with one of the largest parliamentary majorities in decades.', 'Domestic Policy', 92, 0.35, 'VERIFIED', 10800000),
    ],
    DE: [
      art('Germany\'s Economy Contracts 0.3% — Second Quarter in Recession', 'Europe\'s largest economy enters technical recession.', 'https://example.com/de-recession', 'DW News', 'https://dw.com', 'Germany\'s GDP contracted 0.3% in Q3, marking a second consecutive decline and a technical recession. High energy costs and weak Chinese demand continue to weigh on the industrial base.', 'Economic Outlook', 91, -0.65, 'VERIFIED', 0),
      art('Volkswagen Cuts 35,000 Jobs in Largest Restructuring in Decades', 'EV transition pressure forces sweeping layoffs.', 'https://example.com/de-vw', 'Spiegel International', 'https://spiegel.de', 'Volkswagen plans to eliminate 35,000 jobs by 2030 as it accelerates EV production and faces rising Chinese competition. Union leaders called the announcement "devastating" for Germany.', 'Corporate Intelligence', 88, -0.72, 'VERIFIED', 5400000),
      art('Bundestag Passes €50bn Digital and Green Infrastructure Bill', 'Germany commits to AI hubs, 5G expansion, and smart grid.', 'https://example.com/de-digital', 'Handelsblatt', 'https://handelsblatt.com', 'The Bundestag passed a landmark €50 billion investment bill targeting AI research, 5G rollout, and smart energy grid upgrades. The legislation passed with cross-party support.', 'Domestic Policy', 87, 0.55, 'VERIFIED', 10800000),
    ],
    FR: [
      art('Macron Calls Snap Elections After Budget Defeat', 'French government loses confidence vote on spending plan.', 'https://example.com/fr-election', 'France 24', 'https://france24.com', 'President Macron announced snap legislative elections after his minority government\'s budget was rejected in the National Assembly. Bond yields spiked as political uncertainty mounted.', 'Domestic Policy', 87, -0.55, 'VERIFIED', 0),
      art('Paris 2024 Legacy: French Tourism Revenue Hits Record €100bn', 'Olympic Games transformed France\'s global visitor appeal.', 'https://example.com/fr-tourism', 'Le Monde', 'https://lemonde.fr', 'France\'s tourism revenue hit €100 billion following the Paris Olympics, with international arrivals up 18%. Cultural tourism is expected to sustain the growth into 2025.', 'Economic Outlook', 83, 0.70, 'VERIFIED', 5400000),
      art('French Nuclear Fleet Hits 80% Uptime — New Reactors Confirmed', 'EDF recovers capacity as France doubles down on nuclear.', 'https://example.com/fr-nuclear', 'RFI', 'https://rfi.fr', 'EDF reported 80% nuclear fleet uptime following years of outages. Six new reactors are now under construction as France reinforces nuclear power as its clean energy cornerstone.', 'Energy Transition', 84, 0.50, 'VERIFIED', 10800000),
    ],
    PL: [
      art('Poland\'s GDP Grows 3.1% — Fastest in EU on Defence Boom', 'Warsaw\'s military spending surge drives economic outperformance.', 'https://example.com/pl-gdp', 'Rzeczpospolita', 'https://rp.pl', 'Poland grew 3.1% in the latest quarter, the fastest in the EU, driven by record defence spending and infrastructure investment. Warsaw has pledged 4% of GDP to defence, double the NATO target.', 'Economic Outlook', 85, 0.55, 'VERIFIED', 0),
      art('Poland Hosts 300,000 Ukrainian Refugees as Integration Costs Surge', 'Warsaw seeks EU burden-sharing as refugee support reaches €4bn.', 'https://example.com/pl-refugees', 'TVN24', 'https://tvn24.pl', 'Poland hosts 300,000 Ukrainian refugees, the largest concentration in the EU. The government is seeking EU reimbursement for integration costs that have exceeded €4 billion.', 'Geopolitical Tension', 82, -0.30, 'VERIFIED', 5400000),
      art('Tusk Government Restores Rule of Law — EU Funds Resume', 'Warsaw unblocks €35bn in frozen EU cohesion funds.', 'https://example.com/pl-eu', 'Gazeta Wyborcza', 'https://wyborcza.pl', 'The Tusk government\'s judicial reforms unlocked €35 billion in EU cohesion funds frozen under the previous PiS government. Brussels confirmed the rule-of-law benchmarks have been met.', 'Domestic Policy', 86, 0.60, 'VERIFIED', 10800000),
    ],

    // ── Asia-Pacific ─────────────────────────────────────────────────────────
    IN: [
      art('India\'s ISRO Achieves Historic Moon South Pole Landing', 'Chandrayaan-3 successfully deploys Pragyan rover near lunar south pole.', 'https://example.com/in-isro', 'NDTV', 'https://ndtv.com', 'ISRO\'s Chandrayaan-3 made India the first nation to land near the Moon\'s south pole, deploying the Pragyan rover. The mission aims to study water-ice deposits in permanently shadowed craters.', 'Space Exploration', 92, 0.88, 'VERIFIED', 0),
      art('RBI Holds Repo Rate at 6.5% as India\'s CPI Stays Elevated', 'India\'s central bank stays cautious amid food price pressures.', 'https://example.com/in-rbi', 'Economic Times', 'https://economictimes.indiatimes.com', 'The Reserve Bank of India held its repo rate at 6.5%, citing sticky food inflation. GDP growth is tracking at 7.2%, making India the fastest-growing major economy.', 'Monetary Policy', 89, 0.20, 'VERIFIED', 5400000),
      art('India and US Sign Critical Minerals Partnership for EV Supply Chains', 'New Delhi secures lithium and rare earth access deal with Washington.', 'https://example.com/in-us-minerals', 'The Hindu', 'https://thehindu.com', 'India and the United States signed a Critical Minerals Partnership to secure rare earth and lithium supplies for EV and defence industries. The deal strengthens the Quad strategic framework.', 'Geopolitical Tension', 87, 0.45, 'VERIFIED', 10800000),
    ],
    JP: [
      art('Bank of Japan Ends Negative Rates in Historic Policy Shift', 'BoJ raises benchmark rate for first time since 2007.', 'https://example.com/jp-boj', 'Nikkei Asia', 'https://asia.nikkei.com', 'The Bank of Japan ended its negative interest rate policy for the first time since 2007, raising the benchmark rate to 0.1%. The move signals confidence in Japan\'s sustained wage-driven inflation.', 'Monetary Policy', 92, 0.30, 'VERIFIED', 0),
      art('Toyota Unveils Solid-State Battery EV With 1,200km Range', 'Japanese automaker claims breakthrough in next-gen electric vehicles.', 'https://example.com/jp-toyota', 'Japan Times', 'https://japantimes.co.jp', 'Toyota unveiled a prototype EV powered by solid-state batteries delivering 1,200 km of range per charge. Mass production is planned for 2027, representing a major technological leap.', 'Automotive Technology', 87, 0.78, 'VERIFIED', 5400000),
      art('Japan Strengthens Pacific Alliance With Largest US Joint Military Drill', 'Exercise Orient Shield involves 55,000 personnel across land, air, sea.', 'https://example.com/jp-drill', 'NHK World', 'https://nhk.or.jp', 'Japan and the US launched their largest-ever joint military exercise, involving 55,000 personnel in Pacific land, sea, and air operations. The drills come amid heightened tensions with China and North Korea.', 'Geopolitical Tension', 88, -0.35, 'VERIFIED', 10800000),
    ],
    CN: [
      art('China\'s Evergrande Ordered to Liquidate — Largest Property Bankruptcy', 'Hong Kong court ruling triggers seismic shock in real estate sector.', 'https://example.com/cn-evergrande', 'South China Morning Post', 'https://scmp.com', 'A Hong Kong court ordered the liquidation of China Evergrande Group, the world\'s most indebted property developer. The ruling threatens to deepen China\'s prolonged real estate crisis.', 'Economic Outlook', 88, -0.80, 'VERIFIED', 0),
      art('China Launches 200 Exaflop National AI Supercomputer Cluster', 'Beijing unveils state-backed AI infrastructure rivalling US capabilities.', 'https://example.com/cn-ai', 'CGTN', 'https://cgtn.com', 'China unveiled its largest AI supercomputing facility delivering 200 exaflops, a significant step in Beijing\'s ambition to achieve AI dominance by 2030. The cluster is state-funded and classified.', 'DeepTech Venture Capital', 72, 0.60, 'UNVERIFIED', 5400000),
      art('PBoC Cuts Reserve Ratio, Injecting $140bn Into Banking System', 'China\'s central bank eases monetary policy to combat deflation.', 'https://example.com/cn-pboc', 'Caixin Global', 'https://caixin.com', 'The People\'s Bank of China cut the reserve requirement ratio by 50 basis points, releasing approximately $140 billion of liquidity. The move signals growing concern about deflationary pressure.', 'Monetary Policy', 83, 0.25, 'VERIFIED', 10800000),
    ],
    KR: [
      art('Samsung Posts Record Chip Profits on AI Memory Demand Surge', 'HBM chip revenues drive 1,452% profit jump at South Korean giant.', 'https://example.com/kr-samsung', 'Korea Herald', 'https://koreaherald.com', 'Samsung Electronics posted record quarterly profits driven by surging demand for high-bandwidth memory chips used in AI training. Operating profit jumped 1,452% year-on-year to ₩10.4 trillion.', 'Corporate Intelligence', 93, 0.85, 'VERIFIED', 0),
      art('South Korea Extends Conscription Amid North Korea ICBM Tests', 'Seoul raises mandatory service from 18 to 21 months.', 'https://example.com/kr-military', 'Korea JoongAng Daily', 'https://koreajoongangdaily.joins.com', 'South Korea\'s National Assembly passed legislation extending mandatory military service to 21 months following a series of North Korean ICBM tests. Defence spending is also set to rise 4.5%.', 'Geopolitical Tension', 89, -0.55, 'VERIFIED', 5400000),
      art('K-Pop Industry Generates $12bn — Surpasses Hollywood in Asia', 'South Korean entertainment becomes global cultural powerhouse.', 'https://example.com/kr-kpop', 'Yonhap News', 'https://yonhapnews.co.kr', 'South Korea\'s entertainment industry generated $12 billion in exports, surpassing Hollywood box office revenue across Asia-Pacific. Government hallyu visa programs are accelerating soft power expansion.', 'Economic Outlook', 84, 0.75, 'VERIFIED', 10800000),
    ],
    AU: [
      art('RBA Holds Rates at 4.35% as Inflation Remains Sticky', 'Reserve Bank signals further tightening if prices don\'t cool.', 'https://example.com/au-rba', 'ABC News Australia', 'https://abc.net.au', 'The Reserve Bank of Australia held the cash rate at 4.35%, noting persistent services inflation. The board left the door open for further tightening if CPI does not moderate by mid-year.', 'Monetary Policy', 92, -0.20, 'VERIFIED', 0),
      art('Australia Signs $5bn Critical Minerals Deal With US Pentagon', 'Canberra secures lithium and cobalt export deal with US defence.', 'https://example.com/au-minerals', 'The Australian', 'https://theaustralian.com.au', 'Australia and the US finalised a 10-year Critical Minerals Partnership valued at $5 billion, securing Australian lithium and cobalt exports to US defence and EV manufacturers.', 'Geopolitical Tension', 86, 0.45, 'VERIFIED', 5400000),
      art('Sydney Housing Prices Hit Record $1.6m Amid Supply Crisis', 'Australian property defies rate rises as immigration surges.', 'https://example.com/au-housing', 'Sydney Morning Herald', 'https://smh.com.au', 'Sydney\'s median house price hit a record $1.6 million, driven by surging immigration and persistent supply shortages. Economists warn of deepening affordability crises for first-home buyers.', 'Economic Outlook', 85, -0.40, 'VERIFIED', 10800000),
    ],
    ID: [
      art('Indonesia\'s Prabowo Subianto Elected President by Wide Margin', 'Former general wins with 58% of the vote in world\'s third-largest democracy.', 'https://example.com/id-election', 'Jakarta Post', 'https://thejakartapost.com', 'Prabowo Subianto won Indonesia\'s presidential election with 58% of the vote, succeeding Joko Widodo. Prabowo pledges to continue the Nusantara new capital project and expand social programmes.', 'Domestic Policy', 86, 0.30, 'VERIFIED', 0),
      art('Indonesia Discovers 2 Billion Barrel Oil Reserve Off Borneo', 'State energy firm Pertamina confirms major offshore discovery.', 'https://example.com/id-oil', 'Tempo', 'https://tempo.co', 'Pertamina confirmed a major offshore oil discovery estimated at 2 billion barrels near Borneo. The find marks Indonesia\'s largest new discovery in two decades and could reverse declining output.', 'Energy Transition', 83, 0.65, 'VERIFIED', 5400000),
      art('Indonesia Bans Raw Nickel Exports — Forces Domestic Processing', 'Jakarta\'s resource nationalism reshapes global battery supply chains.', 'https://example.com/id-nickel', 'Reuters', 'https://reuters.com', 'Indonesia\'s export ban on raw nickel ore is forcing global battery manufacturers to build local processing plants. The policy has elevated Indonesia to a critical node in the global EV supply chain.', 'Economic Outlook', 84, 0.50, 'VERIFIED', 10800000),
    ],

    // ── Middle East & Africa ──────────────────────────────────────────────────
    RU: [
      art('Russia Steps Up Missile Strikes on Ukrainian Infrastructure', 'Kremlin targets power grid ahead of winter months.', 'https://example.com/ru-strikes', 'Moscow Times', 'https://themoscowtimes.com', 'Russia launched a series of large-scale missile and drone strikes targeting Ukrainian power infrastructure ahead of winter. International condemnation intensified as millions were left without heating.', 'Geopolitical Tension', 74, -0.80, 'VERIFIED', 0),
      art('Russian Central Bank Hikes Rate to 16% to Combat Inflation', 'Bank of Russia takes record-high stance against 7.5% consumer prices.', 'https://example.com/ru-cbr', 'RT', 'https://rt.com', 'Russia\'s central bank raised its benchmark interest rate to 16%, the highest in years, in an attempt to tame 7.5% annual inflation. The move risks further suppressing consumer spending.', 'Monetary Policy', 70, -0.50, 'UNVERIFIED', 5400000),
      art('Kremlin Redirects Oil Exports to Asia as EU Embargo Bites', 'Russia reorients $80bn in annual crude away from Europe.', 'https://example.com/ru-oil', 'Meduza', 'https://meduza.io', 'Russia has redirected over $80 billion in annual crude exports to Asia, with India and China absorbing most European-sanctioned volumes. The pivot is sustaining state revenues despite Western pressure.', 'Economic Outlook', 73, -0.20, 'UNVERIFIED', 10800000),
    ],
    UA: [
      art('Ukraine Produces 1 Million Drones in 2024 — Wartime Industrial Miracle', 'Kyiv transforms drone manufacturing from zero to global leader.', 'https://example.com/ua-drones', 'Kyiv Independent', 'https://kyivindependent.com', 'Ukraine domestically produced over one million drones in 2024, creating a major new industry employing 200,000 workers. The achievement has become a blueprint for wartime industrial mobilisation.', 'Geopolitical Tension', 84, 0.30, 'VERIFIED', 0),
      art('IMF Disburses $900m to Stabilise Ukraine\'s Hryvnia', 'Kyiv\'s wartime fiscal programme stays on track with international support.', 'https://example.com/ua-imf', 'Ukrinform', 'https://ukrinform.net', 'The IMF approved a $900 million disbursement to Ukraine to stabilise the hryvnia and fund wartime fiscal operations. Total committed international aid to Ukraine now exceeds $90 billion.', 'Economic Outlook', 85, 0.20, 'VERIFIED', 5400000),
      art('Zelensky Calls for F-16 Delivery Acceleration at NATO Summit', 'Ukrainian president urges faster Western fighter jet transfer.', 'https://example.com/ua-nato', 'UNIAN', 'https://unian.info', 'President Zelensky addressed NATO leaders, demanding accelerated delivery of F-16 fighter jets pledged by Denmark, the Netherlands, and Norway. The aircraft are expected to change the air war dynamic.', 'Geopolitical Tension', 82, -0.40, 'VERIFIED', 10800000),
    ],
    IL: [
      art('IDF Announces Tactical Pause in Gaza Operations', 'Israeli military creates corridor for humanitarian aid convoys.', 'https://example.com/il-idf', 'Times of Israel', 'https://timesofisrael.com', 'The IDF announced a daily tactical pause in operations along a southern Gaza corridor to allow humanitarian aid convoys. The US, EU and UN welcomed the move while calling for a full ceasefire.', 'Geopolitical Tension', 76, -0.70, 'UNVERIFIED', 0),
      art('Israel\'s Tech Sector Raises $8bn Despite Ongoing Conflict', 'Startup nation defies war with record VC investment in AI and cybersecurity.', 'https://example.com/il-vc', 'Haaretz', 'https://haaretz.com', 'Israeli startups attracted $8 billion in venture capital despite the ongoing conflict. AI cybersecurity and agritech led funding rounds, with many founders relocating R&D teams abroad.', 'DeepTech Venture Capital', 83, 0.45, 'VERIFIED', 5400000),
      art('Netanyahu Coalition Facing Budget Impasse on Haredi Draft Law', 'Ultra-Orthodox coalition members block budget over military exemptions.', 'https://example.com/il-budget', 'Jerusalem Post', 'https://jpost.com', 'Israel\'s coalition government faces a budget crisis after ultra-Orthodox parties refused to accept military draft obligations tied to state funding. A budget failure could trigger early elections.', 'Domestic Policy', 80, -0.40, 'VERIFIED', 10800000),
    ],
    SA: [
      art('Saudi Aramco Posts $121bn Profit — Launches AI Division', 'World\'s largest oil company bets on artificial intelligence for diversification.', 'https://example.com/sa-aramco', 'Arab News', 'https://arabnews.com', 'Saudi Aramco posted a $121 billion annual profit and announced Aramco Digital, a new AI and cloud computing division. The move is central to Vision 2030\'s goal of economic diversification.', 'Corporate Intelligence', 86, 0.60, 'VERIFIED', 0),
      art('NEOM\'s The Line Scaled to 2.4km Phase-One Amid Cost Overruns', 'Saudi giga-project faces engineering and financial reality check.', 'https://example.com/sa-neom', 'Saudi Gazette', 'https://saudigazette.com.sa', 'Saudi Arabia\'s NEOM project scaled The Line\'s first phase to 2.4 km, down from the 170 km mega-city vision. Cost overruns and construction challenges forced a phased re-scoping.', 'Economic Outlook', 78, -0.25, 'UNVERIFIED', 5400000),
      art('Saudi Arabia Opens Tourism to 60 New Nationalities — 100m Visitor Goal', 'Kingdom fast-tracks e-visa system as part of Vision 2030 diversification.', 'https://example.com/sa-tourism', 'Al-Monitor', 'https://al-monitor.com', 'Saudi Arabia extended its e-visa programme to 60 new nationalities as it targets 100 million annual visitors by 2030. Riyadh\'s tourism strategy aims to reduce oil dependency by 2035.', 'Domestic Policy', 82, 0.55, 'VERIFIED', 10800000),
    ],
    NG: [
      art('Nigeria\'s Naira Hits Record Low After CBN Floats Currency', 'Unification of exchange rates triggers sharp devaluation.', 'https://example.com/ng-naira', 'Premium Times', 'https://premiumtimesng.com', 'Nigeria\'s naira fell to a record low after the Central Bank unifiedmultiple exchange rate windows, effectively floating the currency. The move is backed by IMF but triggers inflation concerns for ordinary Nigerians.', 'Monetary Policy', 82, -0.65, 'VERIFIED', 0),
      art('Lagos Launches West Africa\'s Largest Tech Hub at Yaba', '₦50bn investment positions Lagos as Africa\'s Silicon Valley rival.', 'https://example.com/ng-tech', 'BusinessDay', 'https://businessday.ng', 'Lagos state inaugurated West Africa\'s largest technology hub at Yaba, backed by ₦50 billion in government and private investment. The facility aims to house 10,000 tech workers by 2026.', 'DeepTech Venture Capital', 79, 0.65, 'VERIFIED', 5400000),
      art('Nigeria Discovers Major Gas Reserves in Anambra Basin', 'NNPC confirms 200 billion cubic feet deposit in southeast Nigeria.', 'https://example.com/ng-gas', 'Punch Nigeria', 'https://punchng.com', 'Nigeria\'s NNPC confirmed a 200 billion cubic feet natural gas discovery in the Anambra Basin. The find could accelerate Nigeria\'s domestic gas utilisation and reduce reliance on oil revenues.', 'Energy Transition', 80, 0.50, 'VERIFIED', 10800000),
    ],
    ZA: [
      art('South Africa\'s GNU Coalition Passes First Joint Budget', 'ANC-DA Government of National Unity agrees on fiscal framework.', 'https://example.com/za-budget', 'Daily Maverick', 'https://dailymaverick.co.za', 'South Africa\'s Government of National Unity successfully passed its first joint budget, a milestone for the ANC-DA coalition. The budget prioritises infrastructure and Eskom stabilisation.', 'Domestic Policy', 87, 0.40, 'VERIFIED', 0),
      art('Eskom Stage 6 Loadshedding Costs Economy R2bn a Day', 'Power crisis deepens as coal fleet degradation accelerates.', 'https://example.com/za-eskom', 'Business Live', 'https://businesslive.co.za', 'South Africa\'s Stage 6 load-shedding is costing the economy an estimated R2 billion per day in lost output. Eskom cited record levels of unplanned outages as ageing coal plants fail.', 'Economic Outlook', 88, -0.80, 'VERIFIED', 5400000),
      art('Cape Town Completes Third Desalination Plant — Water Secure to 2030', 'Mother City achieves climate-resilient water independence.', 'https://example.com/za-water', 'News24', 'https://news24.com', 'Cape Town completed its third large-scale desalination plant, securing the city\'s water supply through 2030. The R6 billion project ends dependence on rainfall-fed Theewaterskloof dam.', 'Environmental Crisis', 84, 0.55, 'VERIFIED', 10800000),
    ],
    EG: [
      art('Egypt Secures $8bn IMF Deal to Rescue Ailing Economy', 'Cairo accepts sweeping reforms in exchange for emergency lending.', 'https://example.com/eg-imf', 'Egypt Independent', 'https://egyptindependent.com', 'Egypt reached an $8 billion agreement with the IMF, the largest in the country\'s history. Cairo agreed to let the pound float freely and cut fuel subsidies as part of the reform package.', 'Monetary Policy', 83, -0.35, 'VERIFIED', 0),
      art('Suez Canal Revenue Drops 40% as Red Sea Attacks Divert Shipping', 'Houthi strikes force vessels to reroute around Cape of Good Hope.', 'https://example.com/eg-suez', 'Daily News Egypt', 'https://dailynewsegypt.com', 'Suez Canal revenues fell 40% as Houthi attacks in the Red Sea forced shipping companies to reroute cargo around Africa. Egypt loses approximately $1 billion monthly from the disruption.', 'Geopolitical Tension', 85, -0.70, 'VERIFIED', 5400000),
      art('Egypt Inaugurates Africa\'s Largest Solar Farm at Aswan', '1.8GW Benban project powers 1.8 million homes with clean energy.', 'https://example.com/eg-solar', 'Egypt Today', 'https://egypttoday.com', 'Egypt inaugurated a second phase expansion of the Benban Solar Complex near Aswan, making it Africa\'s largest solar installation at 1.8GW. The project is part of Egypt\'s commitment to 42% renewable energy by 2035.', 'Energy Transition', 82, 0.65, 'VERIFIED', 10800000),
    ],

    // ── South Asia & Central Asia ─────────────────────────────────────────────
    PK: [
      art('Pakistan Secures $3bn IMF Bailout to Avert Default', 'Islamabad accepts strict fiscal conditions for emergency lending.', 'https://example.com/pk-imf', 'Dawn', 'https://dawn.com', 'The IMF approved a $3 billion standby arrangement for Pakistan, providing critical relief as forex reserves fell below $4 billion. Strict conditions include subsidy cuts and tax reforms.', 'Economic Outlook', 85, -0.30, 'VERIFIED', 0),
      art('Imran Khan Convicted, PTI Protests Erupt Nationwide', 'Former PM sentenced as supporters clash with security forces.', 'https://example.com/pk-imran', 'The News International', 'https://thenews.com.pk', 'Former Prime Minister Imran Khan was convicted on corruption charges amid widespread protests by his PTI party. Human rights groups condemned the trial as politically motivated.', 'Domestic Policy', 76, -0.65, 'UNVERIFIED', 5400000),
      art('Pakistan IT Exports Hit $3.2bn — Tech Sector Emerges as Bright Spot', 'Freelancing and software exports surge 26% amid economic headwinds.', 'https://example.com/pk-tech', 'Tribune Pakistan', 'https://tribune.com.pk', 'Pakistan\'s IT exports crossed $3.2 billion, growing 26% annually. The government targets $5 billion by 2025 through new technology special economic zones and freelancer tax incentives.', 'Corporate Intelligence', 80, 0.65, 'VERIFIED', 10800000),
    ],

    // ── Others ────────────────────────────────────────────────────────────────
    TR: [
      art('Turkey\'s Inflation Hits 75% — Central Bank Raises Rate to 50%', 'Ankara implements orthodox monetary tightening after years of resistance.', 'https://example.com/tr-inflation', 'Hurriyet Daily News', 'https://hurriyetdailynews.com', 'Turkey\'s annual inflation reached 75%, prompting the central bank to raise rates to 50%. President Erdogan endorsed the tightening pivot after years of opposing rate rises.', 'Monetary Policy', 83, -0.70, 'VERIFIED', 0),
      art('Istanbul Named Europe\'s Fastest-Growing Tech Startup Hub', 'Turkish ecosystem attracts $4bn VC amid diaspora return wave.', 'https://example.com/tr-tech', 'Daily Sabah', 'https://dailysabah.com', 'Istanbul ranked as Europe\'s fastest-growing tech hub in 2024, attracting $4 billion in venture capital. A wave of Turkish tech diaspora returning from Berlin and London is accelerating growth.', 'DeepTech Venture Capital', 79, 0.65, 'VERIFIED', 5400000),
      art('Turkey Brokers Black Sea Grain Corridor Extension', 'Ankara mediates renewed deal between Kyiv and Moscow.', 'https://example.com/tr-grain', 'TRT World', 'https://trtworld.com', 'Turkey brokered a two-month extension of the Black Sea Grain Initiative, securing continued Ukrainian grain exports through Turkish-controlled straits. Turkey won concessions on Russian fertiliser exports.', 'Geopolitical Tension', 76, 0.30, 'UNVERIFIED', 10800000),
    ],
    IR: [
      art('Iran Enriches Uranium to 83.7% — Near Weapons Grade, IAEA Warns', 'Tehran\'s nuclear programme advances despite international pressure.', 'https://example.com/ir-nuclear', 'Al Jazeera', 'https://aljazeera.com', 'The IAEA confirmed Iran has enriched uranium to 83.7%, just below weapons-grade threshold. The development sharply escalates nuclear tensions and triggers emergency UN Security Council session.', 'Geopolitical Tension', 80, -0.85, 'VERIFIED', 0),
      art('Iran Launches Domestically Built Destroyer Dena Into Persian Gulf', 'Tehran showcases naval expansion amid rising regional tensions.', 'https://example.com/ir-navy', 'Press TV', 'https://presstv.ir', 'Iran launched the domestically-built Dena destroyer, its most advanced naval vessel, into the Persian Gulf. The launch is seen as a strategic message amid ongoing tensions with the US and Israel.', 'Geopolitical Tension', 65, -0.55, 'UNVERIFIED', 5400000),
      art('Iran\'s Tehran Stock Exchange Rallies as Rial Stabilises', 'Markets rebound as nuclear talks reopen and sanctions relief expected.', 'https://example.com/ir-markets', 'Financial Tribune', 'https://financialtribune.com', 'Tehran\'s stock exchange rallied 12% in a week as the Iranian rial stabilised following signals of renewed nuclear negotiations. International investors monitor developments for potential sanctions relief.', 'Economic Outlook', 70, 0.40, 'UNVERIFIED', 10800000),
    ],
  };

  // Smart default for unknown countries — uses the country name not the code
  const name = countryCode; // fallback label
  const defaultSet: AnalyzedArticle[] = [
    art(`${name} Economic Outlook: Growth Revised Amid Global Headwinds`, 'International analysts revise forecasts for the region.', `https://example.com/${countryCode.toLowerCase()}-economy`, 'Reuters', 'https://reuters.com', `Economic growth forecasts for ${name} have been revised as global headwinds — including high interest rates, slowing Chinese demand, and geopolitical tensions — weigh on the outlook. Domestic factors remain a key variable.`, 'Economic Outlook', 72, 0.15, 'UNVERIFIED', 0),
    art(`${name} Advances Regional Diplomacy at Multilateral Forum`, 'Government signals openness to new trade and security frameworks.', `https://example.com/${countryCode.toLowerCase()}-diplomacy`, 'Al Jazeera', 'https://aljazeera.com', `${name}'s government has intensified diplomatic engagement, participating in multilateral forums on trade, security, and climate. Officials signal a recalibration of strategic priorities in the coming year.`, 'Geopolitical Tension', 70, 0.20, 'UNVERIFIED', 5400000),
    art(`${name} Targets 40% Renewable Energy by 2030`, 'National energy plan accelerates clean power investment.', `https://example.com/${countryCode.toLowerCase()}-energy`, 'Financial Times', 'https://ft.com', `${name} unveiled an updated national energy plan targeting 40% renewable generation by 2030. Solar, wind, and grid modernisation projects are in various stages of tender and construction.`, 'Energy Transition', 74, 0.45, 'UNVERIFIED', 10800000),
  ];

  return sets[countryCode] || defaultSet;
}

export const MOCK_BREAKING_NEWS: GlobePoint[] = [
  { lat: 38.9072, lng: -77.0369, intensity: 0.9, label: 'Washington DC', country: 'US' },
  { lat: 51.5074, lng: -0.1278,  intensity: 0.85, label: 'London',        country: 'GB' },
  { lat: 48.8566, lng: 2.3522,   intensity: 0.75, label: 'Paris',         country: 'FR' },
  { lat: 35.6762, lng: 139.6503, intensity: 0.82, label: 'Tokyo',         country: 'JP' },
  { lat: 28.6139, lng: 77.2090,  intensity: 0.88, label: 'New Delhi',     country: 'IN' },
  { lat: 39.9042, lng: 116.4074, intensity: 0.78, label: 'Beijing',       country: 'CN' },
  { lat: -23.5505,lng: -46.6333, intensity: 0.65, label: 'São Paulo',     country: 'BR' },
  { lat: 55.7558, lng: 37.6173,  intensity: 0.72, label: 'Moscow',        country: 'RU' },
  { lat: 30.0444, lng: 31.2357,  intensity: 0.60, label: 'Cairo',         country: 'EG' },
  { lat: -33.8688,lng: 151.2093, intensity: 0.55, label: 'Sydney',        country: 'AU' },
  { lat: 37.5665, lng: 126.9780, intensity: 0.70, label: 'Seoul',         country: 'KR' },
  { lat: 52.5200, lng: 13.4050,  intensity: 0.68, label: 'Berlin',        country: 'DE' },
  { lat: 6.5244,  lng: 3.3792,   intensity: 0.62, label: 'Lagos',         country: 'NG' },
  { lat: -26.2041,lng: 28.0473,  intensity: 0.58, label: 'Johannesburg',  country: 'ZA' },
  { lat: 41.0082, lng: 28.9784,  intensity: 0.64, label: 'Istanbul',      country: 'TR' },
];

